set(BUILD_INFO_PATH "${CMAKE_BINARY_DIR}/build_info.h")
set(TEMP_BUILD_INFO_PATH "${CMAKE_BINARY_DIR}/build_info.tmp.h")

file(WRITE "${TEMP_BUILD_INFO_PATH}" "// This file is generated by CMake. Do not edit it manually.\n\n")
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#pragma once\n\n")

execute_process(
        COMMAND git rev-parse HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        OUTPUT_VARIABLE ORPHAN_BUILD_VERSION
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define ORPHAN_BUILD_VERSION \"${ORPHAN_BUILD_VERSION}\"\n")
message(STATUS "Build version: ${ORPHAN_BUILD_VERSION}")

string(SUBSTRING "${ORPHAN_BUILD_VERSION}" 0 7 ORPHAN_BUILD_VERSION_SHORT)
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define ORPHAN_BUILD_VERSION_SHORT \"${ORPHAN_BUILD_VERSION_SHORT}\"\n")
message(STATUS "Build version (short): ${ORPHAN_BUILD_VERSION_SHORT}")

execute_process(
        COMMAND git rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        OUTPUT_VARIABLE ORPHAN_BUILD_BRANCH
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define ORPHAN_BUILD_BRANCH \"${ORPHAN_BUILD_BRANCH}\"\n")
message(STATUS "Build branch: ${ORPHAN_BUILD_BRANCH}")

execute_process(
        COMMAND git log -1 --pretty=%B
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        OUTPUT_VARIABLE ORPHAN_BUILD_COMMIT_MESSAGE
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(REGEX REPLACE "\n.*" "" ORPHAN_BUILD_COMMIT_MESSAGE "${ORPHAN_BUILD_COMMIT_MESSAGE}")
string(REPLACE "\"" "\\\"" ORPHAN_BUILD_COMMIT_MESSAGE "${ORPHAN_BUILD_COMMIT_MESSAGE}")
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define ORPHAN_BUILD_COMMIT_MESSAGE \"${ORPHAN_BUILD_COMMIT_MESSAGE}\"\n")
message(STATUS "Build commit message: ${ORPHAN_BUILD_COMMIT_MESSAGE}")

execute_process(
        COMMAND git diff --name-only HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        OUTPUT_VARIABLE ORPHAN_FILES_CHANGED
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(LENGTH "${ORPHAN_FILES_CHANGED}" ORPHAN_FILES_CHANGED_LENGTH)
string(REGEX REPLACE "\n" ";" ORPHAN_FILES_CHANGED_LIST "${ORPHAN_FILES_CHANGED}")
list(LENGTH ORPHAN_FILES_CHANGED_LIST ORPHAN_FILES_CHANGED_COUNT)
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define ORPHAN_FILES_CHANGED_COUNT ${ORPHAN_FILES_CHANGED_COUNT}\n")
message(STATUS "Files changed: ${ORPHAN_FILES_CHANGED_COUNT}")

execute_process(
        COMMAND whoami
        OUTPUT_VARIABLE ORPHAN_PC_USERNAME
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(REPLACE "\\" "/" ORPHAN_PC_USERNAME "${ORPHAN_PC_USERNAME}")
message(STATUS "PC username: ${ORPHAN_PC_USERNAME}")
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define ORPHAN_PC_USERNAME \"${ORPHAN_PC_USERNAME}\"\n")

execute_process(
        COMMAND powershell -Command "get-appxpackage Microsoft.MinecraftUWP | Select InstallLocation"
        OUTPUT_VARIABLE MC_INSTALL_LOC
        OUTPUT_STRIP_TRAILING_WHITESPACE
)

if ("${MC_INSTALL_LOC}" STREQUAL "")
    set(MC_INSTALL_LOC "Unknown")
    set(ORPHAN_INTENDED_VERSION "Unknown")
    message(WARNING "Minecraft install location: Unknown")
    message(WARNING "Intended version: Unknown")
else()
    string(REPLACE "\\" "/" MC_INSTALL_LOC "${MC_INSTALL_LOC}")
    string(REGEX REPLACE ".*\n" "" MC_INSTALL_LOC "${MC_INSTALL_LOC}")
    set(MC_INSTALL_LOC "${MC_INSTALL_LOC}/Minecraft.Windows.exe")

    message(STATUS "Minecraft install location: ${MC_INSTALL_LOC}")

    execute_process(
            COMMAND powershell -Command "(Get-Command \"${MC_INSTALL_LOC}\").Version"
            OUTPUT_VARIABLE MC_VERSION
            OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    string(REGEX REPLACE ".*\n" "" MC_VERSION "${MC_VERSION}")
    string(REGEX REPLACE " +" "." MC_VERSION "${MC_VERSION}")
    set(ORPHAN_INTENDED_VERSION "${MC_VERSION}")
    message(STATUS "Intended version: ${ORPHAN_INTENDED_VERSION}")
endif()

file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define ORPHAN_INTENDED_VERSION \"${ORPHAN_INTENDED_VERSION}\"\n")

execute_process(
        COMMAND ${CMAKE_COMMAND} -E compare_files "${TEMP_BUILD_INFO_PATH}" "${BUILD_INFO_PATH}"
        RESULT_VARIABLE FILES_DIFFER
)

if (FILES_DIFFER)
    message(STATUS "Updating build_info.h")
    file(RENAME "${TEMP_BUILD_INFO_PATH}" "${BUILD_INFO_PATH}")
else()
    message(STATUS "No changes to build_info.h")
    file(REMOVE "${TEMP_BUILD_INFO_PATH}")
endif()
